### ISSUE TITLE
No location_code or location_code_type

### ISSUE THREAD

**Issue by jebyrnes** [debusklaneml/CanadaC19#1]
Note - these two columns are missing, and are needed to standardize across data sets. They are required by the standard.

**Comment by debusklaneml** [comment]
@jebyrnes I see, these standardized variables were not simply suggestive, but required in each package. I see. My initial interpretation was that if the data was readily available, then standardize according to the documentation, if not, then leave out. Perhaps this could be clarified or I simply missed it (probably the later). I'll work to add them in.

**Comment by debusklaneml** [comment]
These two columns have been added as per the documentation.
