### ISSUE TITLE
pkgdown?

### ISSUE THREAD

**Issue by jebyrnes** [debusklaneml/CanadaC19#2]
Weird - I keep getting pkgdown html for issues.... have you generated a pkgdown site and/or made it available via github pages?

**Comment by debusklaneml** [comment]
@jebyrnes No, I have not. I followed along with the French package already onboard that did not have a pkgdown site. This is something I planned to add later (simply because I've never done it before and it did not appear to be required). 

Is this something that needs to be done?

**Comment by debusklaneml** [comment]
pkgdown site is live.

**Comment by jebyrnes** [comment]
Nice! BTW: Proper URL is https://debusklaneml.github.io/CanadaC19/
